// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCore.Entity.Models
{
    public partial class JobApplication_Details
    {
        public int Person_ID { get; set; }
        public string Applicant_Resume { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public int Age { get; set; }
        public string Full_Name { get; set; }
        public int SSLC_Marks { get; set; }
        public int HSC_Marks { get; set; }
        public decimal Graduation_Percent { get; set; }
        public string Skills { get; set; }
        public string Interests { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}